name: Update

on:
  schedule:
    - cron: "0 12 * * 1-5"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    name: Commit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python src/mhlw.py
          python src/y.py
          python src/hot.py

      - name: Commit & Push
        run: |
          today=`date "+%Y-%m-%d"`
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add data; \
            git commit -m "${today}"; \
            git push origin main; \
          fi

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "errorlog.txt"

      - name: On catch exceptions
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          cat errorlog.txt
          exit 1
