name: Update

on:
  schedule:
    - cron: "0 12 * * 1-5"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    name: Commit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python src/main.py

      - name: Commit & Push
        run: |
          today=`date "+%Y-%m-%d"`
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config core.quotepath false

          if (git diff --shortstat | grep '[0-9]'); then \
            git add data --verbose; \
            git commit -m "${today}"; \
            git push origin main; \
          fi

      - name: Check for errors
        run: |
          if [ -f "errorlog.txt" ]; then
            cat errorlog.txt
            exit 1
          fi
